# Generated by Django 5.2.7 on 2025-11-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_chicken', models.IntegerField()),
                ('feed_intake', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('light', models.FloatField()),
                ('ammonia', models.FloatField()),
                ('noise', models.FloatField()),
                ('prediction_result', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
